# Generated by Django 5.0.3 on 2024-04-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profile-image/020.jpg', null=True, upload_to=''),
        ),
    ]
