# Generated by Django 5.0.3 on 2024-04-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profile-image/020.jpg', null=True, upload_to='images/profile_pic_upload_path'),
        ),
    ]
